spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/transithub
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true